### ISSUE TITLE
Request: Linux builds for Raspberry Pi (arm64)

### ISSUE THREAD

**Issue by merwok** [quinton-ashley/nostlan#18]
Hello!  I like the concept of this project.  I’m making a handheld with a raspberry pi zero and an LCD screen and looking for a nice, small frontend.  The wiki mentions that a good computer is needed to display huge images and animations and such.  But is this also adequate for a small computer with a small screen?

**Comment by quinton-ashley** [comment]
There's some more work I need to do to optimize Nostlan for less powerful devices.  I also need to learn how to build an ARM AppImage that can run on the Raspberry Pi.  The linux build is for x64 systems not ARM.  I'll let you know when I make an ARM build for the Pi cause I'll need you to test it since I don't have one myself.

As of v1.10.x the animations are done with thumbnail images so performance is much better than it was before.  The thumbnails for viewing on the main game library view are a set size of 720 px in height, that's optimal for 4K.  When clicking on a cover it loads the full size image, which sometimes even on my pc causes the app to lag and makes covers disappear for a split second so I need to solve that problem.  Don't know how to do that yet but I have a few ideas.

I'm going to add some options to change the thumbnail and full screen heights in the user preferences file in the next version.  I also want to make a simple toggle in the appearance settings that will let users set their preferred resolution which would change those resize values automatically.  I also want to add an option to delete the original image files so they don't take up so much space too.

**Comment by merwok** [comment]
That’s good to hear!  so I guess the two questions are:

- Could there be a setting to control the picture size and quality?  don’t need 4K for a 3.5" screen :slightly_smiling_face: 

- How to easily install on a raspberry pi?  I would personally prefer to avoid external systems like flatpak or appimage: I think I will give a try to dockcross to run npm install / build on my laptop, then copy the whole app to the pi.  The idea way would be to get a deb package for raspbian, but that’s probably harder to do.

**Comment by quinton-ashley** [comment]
Nostlan's power draw is very minimal, it's similar to having one tab open in a browser.  It does stay open in the background after launching games, this is what makes holding start for 5 seconds to exit the emulator work.  I don't really know that much about Raspberry Pis.  I know you can run Manjaro on them and the ARM AppImage will work just fine.  I personally prefer to embrace external systems like flatpak and AppImage.  At least for now, I'm not interested in doing builds for individual distros and dealing with all the individual package managers out there.

What's the resolution of the 5" screen you want to use?

**Comment by merwok** [comment]
Not sure if I agree with the title change: my target is raspbian, which works on all raspberry architectures (armv6+hf, armv7).

For the screen, for now I have a couple 3.5" screens at 320x480, not sure yet if I’ll go with 4.3" (480x272) or 5" (800x600).

**Comment by quinton-ashley** [comment]
Oh whoops sorry I didn't know that. I will not support Raspbian cause it's 32bit.  Nostlan doesn't support any 32bit operating systems.  Nostlan's UI won't be compatible with screens that are that low res.  Nostlan was made for high resolution displays.

I'm curious why are you considering making a device with such tiny screens?

**Comment by merwok** [comment]
For a handheld console :slightly_smiling_face:

**Comment by merwok** [comment]
I am surprised that an interpreted app cares about the processor architecture.  Doesn’t nodejs run everywhere?

**Comment by merwok** [comment]
> Nostlan was made for high resolution displays.

We have different goals then!  No hurt feelings and good luck to your project!
I may revisit for emulation on the TV.

**Comment by quinton-ashley** [comment]
Is this like a novelty handheld console for a youtube vid or would you actually play games on a 3.5" screen at 480p in 2020?

**Comment by quinton-ashley** [comment]
I still want to support that kind of NES mini type use of the Pi with a TV.  If you're interested in having Nostlan on handheld devices (with much better screens) I'm actually in the early stages of working on Nostlan for iOS.

**Comment by merwok** [comment]
Yes, many people build small handheld console to play NES, SuperNES, GameBoy games, etc.
Are you surprised that people like small devices? :thinking:

> A lot of the newer emulators don't have builds for 32 bit systems either
Ah I didn’t think about that!  The OS provides packages (raspbian includes higan for example) or I build them myself (like the newly revived bsnes with HD mode on my laptop).

> it adds a lot of complexity to the path finding process for emulator apps.
Ah, I didn’t know either that emulators did anything more complicated than looking for executables on `PATH`.

About phones: not a fan of touchscreen controls, and wouldn’t like to play and be interrupted by notifications and such.  (More reasons to make a dedicated handheld!)

**Comment by quinton-ashley** [comment]
I mean, if you think it'd be simple to do and wouldn't take that long feel free to fork Nostlan and give it a go. To start the app use 'electron . --dev' in the main folder.
